runtime: python310

entrypoint: streamlit run trip_app_combined.py --server.port=8080 --server.address=0.0.0.0

instance_class: F2

env_variables:
  STREAMLIT_SERVER_HEADLESS: true
  STREAMLIT_SERVER_PORT: 8080
  STREAMLIT_SERVER_ENABLECORS: false
  STREAMLIT_BROWSER_GATHERUSAGESTATS: false
